### ISSUE TITLE
Using .format instead of .complete doesn't render constraints as strings

### ISSUE THREAD

**Issue by samredai** [KnowledgeForge/keymaker#7]
I'm not sure if this only happens when short circuiting occurs but .format(...) doesn't produce a clean string the way .complete(...) does.

```py
from keymaker import Prompt
from keymaker.constraints import OptionsConstraint
from keymaker.models import Huggingface

prompt = Prompt("there is a library called {}")
filled = asyncio.run(prompt.format(OptionsConstraint({"Keymaker"})))
print(filled)
# there is a library called OptionsConstraint(options={'Keymaker'}, short_circuit=True)
```

As you can see, this doesn't happen with .complete()
```py
from keymaker import Prompt
from keymaker.constraints import OptionsConstraint
from keymaker.models import Huggingface

prompt = Prompt("there is a library called ")
filled = asyncio.run(prompt.complete(model=Huggingface("gpt2"), constraint=OptionsConstraint({"Keymaker"})))
print(filled)
# there is a library called Keymaker
```

**Comment by samredai** [comment]
Nvm...I think it's because I wasn't passing the model in for the first example. The following works:
```py
from keymaker import Prompt
from keymaker.constraints import OptionsConstraint
from keymaker.models import Huggingface

prompt = Prompt("there is a library called {}")
filled = asyncio.run(prompt.format(OptionsConstraint({"Keymaker"})), model=Huggingface("gpt2"), )
print(filled)
# there is a library called Keymaker
```
Should this raise an error when there's no model?

**Comment by CircArgs** [comment]
@samredai 

You want 
```python
from keymaker import Prompt, CompletionConfig
filled = asyncio.run(prompt.format(CompletionConfig(constraint=OptionsConstraint({"Keymaker"}))))
```

This is mentioned in the [getting started docs](https://keymaker.headjack.ai/docs/getting-started/).

What you've done with 
```python
from keymaker import Prompt
from keymaker.constraints import OptionsConstraint
from keymaker.models import Huggingface

prompt = Prompt("there is a library called {}")
filled = asyncio.run(prompt.format(OptionsConstraint({"Keymaker"})))
print(filled)
``` 

is pass a `Stringable` in `OptionsConstraint`. Keymaker saw that what you passed was not requesting a completion but could be cast to a string and so put it into the prompt. Keymaker `Prompt` formatting behaves similarly to python's ordinary `str` formatting in that you can pass ordinary objects and they will be automatically cast. Keymaker of course provides extra functionality to facilitate LLM generation hence the need for `CompletionConfig`s. 

Here are the different types of arguments that can be passed to the .format() method on a prompt object:

- `Stringable`: Any string or object that can be converted to a string, like str, int, etc. This just formats the prompt with that static string.

- `CompletionConfig`: the basic unit of requestion completion. Accepts all parameters necessary to generate a completion.

- `Callable[[Prompt], Union[Stringable, CompletionConfig]]`: A callable that takes the Prompt as an argument and returns either a Stringable or CompletionConfig. This allows dynamically formatting the prompt based on the state of the Prompt.

- `Callable[[Prompt], Generator[Union[Stringable, CompletionConfig]]]`: A callable that takes the Prompt and returns an iterable of Stringable or CompletionConfig objects. This allows dynamically formatting the prompt with multiple components based on the state of the Prompt.

**Comment by samredai** [comment]
@CircArgs that makes sense, thanks! Closing this
